/**
 * List of confirmed-broken external URLs found in CMS content.
 *
 * Source: SiteImprove "Broken link (confirmed)" report 2026-04-13.
 * Only URLs SiteImprove has fetched and verified as 4xx/5xx/DNS-fail
 * are included — "Needs review" entries (CAPTCHAs, rate limits,
 * temporary outages) are deliberately excluded.
 *
 * URLs are stored lowercase. Comparison is also case-insensitive and
 * tolerant of trailing punctuation (`.`, `,`, `;`) that CMS authors
 * sometimes include after a URL.
 *
 * Used by `unwrapBrokenLinks` plugin in `contentSanitizer.js` to
 * convert <a href="dead-url">text</a> into plain text at render time.
 *
 * To regenerate from a fresh SiteImprove export:
 *   1. Download "Pages with broken links" CSV from SiteImprove.
 *   2. Filter rows where status = "Broken link (confirmed)".
 *   3. Extract the URL column, lowercase, dedupe.
 *   4. Replace the BROKEN_URLS array below.
 */

const BROKEN_URLS = [
  "http://bit.ly/2gyffv",
  "http://bit.ly/2kwlraf.",
  "http://bit.ly/2ofvhqg.",
  "http://bit.ly/2onestg",
  "http://bit.ly/2osetoj",
  "http://bit.ly/2pcnkr9",
  "http://bit.ly/2qftnzt",
  "http://bit.ly/2r7mw0s.",
  "http://bit.ly/2r7mw0s",
  "http://bit.ly/2rhgiyl.",
  "http://bit.ly/2rhgiyl",
  "http://bit.ly/2rhmbvr.",
  "http://bit.ly/2rktg5d.",
  "http://bit.ly/2rktg5d",
  "http://bit.ly/2rsblim",
  "http://bit.ly/2sj0nhu.",
  "http://bit.ly/2sj0nhu",
  "http://bit.ly/2sjgoop",
  "http://bit.ly/2skir36",
  "http://bit.ly/2tmysgq",
  "http://bit.ly/2xik2ng",
  "http://bit.ly/2yqors3",
  "http://bit.ly/2yxwksn",
  "http://bit.ly/2yywrtw",
  "http://bit.ly/2yzlcbi",
  "http://chicagocouncil.org/collaboration-for-justice/",
  "http://cit.memphis.edu/publications_files/compton-_review_of_cit_literature.pdf",
  "http://cpp.fullerton.edu/pdf/what%20works.pdf",
  "http://data.bls.gov/cgi-bin/print.pl/news.release/ecopro.t06.htm",
  "http://directives.chicagopolice.org/directives/data/a7a57bf0-12d103eb-84112-d103-f1bd3a851b8bc48e.html",
  "http://dph.illinois.gov/sites/default/files/publications/illinois-opioid-action-plan-sept-6-2017-final.pdf",
  "http://gloucesterpd.com/addicts/",
  "http://ipcsa.org/il-probation-directory",
  "http://kirwaninstitute.osu.edu/research/understanding-implicit-bias/",
  "http://leadkingcounty.org/lead-evaluation/",
  "http://mhs.com/product.aspx?gr=saf&prod=lsi-rs&id=overview",
  "http://nationaltasc.org/wp-content/uploads/2015/10/drug-testing-strategies.pdf",
  "http://navaa.org/budget/index.html",
  "http://ncdsv.org/images/common%20misconceptions%20in%20addressing%20dv%20in%20child%20custody.pdf",
  "http://nicic.gov/evidencebasedpractices",
  "http://nicic.gov/t4c",
  "http://nicic.gov/topics/5288-medication-assisted-treatment-mat-in-corrections",
  "http://nicic.gov/wodp/program/215-cognitive-interventions-program-cgip",
  "http://pcssnow.org/wp-content/uploads/2015/03/stigma-in-methadone-and-buprenorphine-maintenance-treatment-asam-module.pdf",
  "http://sd15.senate.ca.gov/sites/sd15.senate.ca.gov/files/7b.pdf",
  "http://stopoverdoseil.org/naloxone.html",
  "http://www.advancedtrauma.com/index.html",
  "http://www.cdc.gov/violenceprevention/childmaltreatment/definitions.html",
  "http://www.cebc4cw.org/program/seeking-safety-for-adolescents/detailed",
  "http://www.cebc4cw.org/program/trauma-affect-regulation-guide-for-education-and-therapy-adults/detailed",
  "http://www.cebc4cw.org/program/trauma-recovery-and-empowerment-model/detailed",
  "http://www.cfgnh.org/portals/0/uploads/documents/understanding%20gnh/third%20party%20reports/411617-health-and-prisoner-reentry.pdf",
  "http://www.chicagotribune.com/suburbs/daily-southtown/news/ct-sta-calumet-city-shotspotter-st-0404-20180403-story.html",
  "http://www.clasp.org/admin/site/publications_archive/files/0210.pdf",
  "http://www.co.arapahoe.co.us/documentcenter/view/4389/admit-outline-program-description-iirev1-003",
  "http://www.co.lucas.oh.us/2843/dart",
  "http://www.cognitivecentre.ca/rrprogram",
  "http://www.commfit.org/our-services/introduction-to-rochester-forensic-assertive-community-treatment-r-fact/",
  "http://www.cookcountycourt.org/aboutthecourt/countydepartment/domesticviolence/ordersofprotection.aspx",
  "http://www.cookcountycourt.org/portals/0/domestic%20violence%20division/general%20administrative%20orders/2020-dv-04a%20--%202020-dv-14.pdf?ver=2020-04-10-161440-830",
  "http://www.cookcountycourt.org/tabid/210/default.aspx",
  "http://www.csh.org/wp-content/uploads/2011/12/report_doqindicators.pdf",
  "http://www.cssp.org/reform/strengthening-families/resources/body/literaturereview.pdf",
  "http://www.dph.illinois.gov/content/idph-opioid-data-dashboard",
  "http://www.dph.illinois.gov/naloxone",
  "http://www.dph.illinois.gov/sites/default/files/publications/drug-overdose-deaths-aug2018.pdf",
  "http://www.dph.illinois.gov/sites/default/files/publications/drug-overdose-deaths-december2017.pdf",
  "http://www.dph.illinois.gov/sites/default/files/publications/drug-overdose-deaths-july-2018.pdf",
  "http://www.dph.illinois.gov/sites/default/files/publications/heroin-od-report-september-2016.pdf",
  "http://www.east-end.org/2016/09/08/conversation-for-change-2/",
  "http://www.ebcrp.org/services/incarcerated-reentry/fact-tract/",
  "http://www.episcenter.psu.edu/ebp/definition",
  "http://www.episcenter.psu.edu/ebp/strengthening",
  "http://www.illinoisattorneygeneral.gov/women/ordersofprotection.html",
  "http://www.illinoiscourts.gov/2016_statutory_court_fee_task_force_report.pdf",
  "http://www.illinoiscourts.gov/administrative/covid-19.asp",
  "http://www.mhs.com/product.aspx?gr=saf&id=overview&prod=ls-cmi",
  "http://www.mhs.com/product.aspx?gr=saf&id=overview&prod=lsi-r",
  "http://www.ncchc.org/substance-use-disorder-treatment-position-statement",
  "http://www.nchrc.org/law-enforcement/us-law-enforcement-who-carry-naloxone/",
  "http://www.ncja.org/about-ncja/ncja-covid-19",
  "http://www.ncsc.org/~/media/files/pdf/services%20and%20experts/areas%20of%20expertise/sentencing%20probation/ran%20appendix%20a.ashx",
  "http://www.ncsl.org/blog/2017/11/10/veterans-by-the-numbers.aspx",
  "http://www.nimh.nih.gov/index.shtm",
  "http://www.nysap.us/review%20of%20trauma%20screening%20tools%20for%20children%20&%20adolescents.pdf",
  "http://www.ohiomayorsalliance.org/wp-content/uploads/2017/06/cityaddicitonresponse.pdf",
  "http://www.overdosepreventionalliance.org/p/od-prevention-program-locator.html",
  "http://www.pewresearch.org/fact-tank/2017/02/21/5-facts-about-crime-in-the-u-s/",
  "http://www.preventionresearch.org/standardsofevidencebook.pdf",
  "http://www.rupri.org/wpcontent/uploads/behavioral-health-in-rural-americachallenges-and-opportunities.pdf",
  "http://www.shotspotter.com/2017ngi",
  "http://www.sprc.org/sites/default/files/resource-program/suicide-in-the-workplace%20(003).pdf",
  "http://www.thresholds.org/our-work/programs/justice-program/",
  "http://www.tresearch.org/products/assessment-and-evaluation",
  "http://www.whitehouse.gov/ondcp/about",
  "http://www.who.int/csr/disease/swineflu/frequently_asked_questions/levels_pandemic_alert/en/.",
  "http://www.who.int/csr/disease/swineflu/updates/en/.",
  "https://apps.urban.org/features/latino-criminal-justice-data/.washington",
  "https://bha.health.maryland.gov/overdose_prevention/pages/ofr-.aspx",
  "https://bit.ly/2alfjvv",
  "https://bit.ly/2em8nz7",
  "https://bit.ly/2ixj5qr",
  "https://bit.ly/2kbz5rb",
  "https://bit.ly/2kfut1l.",
  "https://bit.ly/2khadb9",
  "https://bit.ly/2koscok",
  "https://bit.ly/2kubmfr",
  "https://bit.ly/2llop0z",
  "https://bit.ly/2lotyfc.",
  "https://bit.ly/2louh4a.",
  "https://bit.ly/2mcnk8y",
  "https://bit.ly/2mdjdml",
  "https://bit.ly/2mhlksy",
  "https://bit.ly/2oqrkxb",
  "https://bit.ly/2qbxydf",
  "https://bit.ly/2qjapzm",
  "https://bit.ly/2vkzzqq",
  "https://bit.ly/2xxwzuv",
  "https://bit.ly/31jpqfl",
  "https://bit.ly/32kzus1",
  "https://bit.ly/33zp5jc",
  "https://bluehelp.org/resources/statistics/",
  "https://cdn.jsdelivr.net/gh/icjia/doit-accessibility/dist/index.js",
  "https://cebcp.org/wp-content/tcmagazine/tc15-fall2018",
  "https://cech.uc.edu/centers/ucci/services/trainings/changing_offender_behavior/cbi-cc-training-overview.html",
  "https://cech.uc.edu/centers/ucci/services/trainings/offender_assessment/orastrainingoverview.html",
  "https://cops.usdoj.gov/default.asp?item=2558",
  "https://cops.usdoj.gov/html/dispatch/06-2014/preventing_officer_suicide.asp",
  "https://cops.usdoj.gov/html/dispatch/09-2013/fairness_as_a_crime_prevention_tool.asp",
  "https://crime-data-explorer.app.cloud.gov/officers/national/united-states/uof",
  "https://csgjusticecenter.org/nrrc/reentry-services-directory/",
  "https://csgjusticecenter.org/nrrc/topics/community-supervision-probation-and-parole/",
  "https://csgjusticecenter.org/wp-content/uploads/2012/12/improving_responses_to_people_with_mental_illnesses_-_the_essential_elements_of_specialize_probation_initiatives.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2012/12/le-essentialelements.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2012/12/mhc-essential-elements.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2013/03/consensus-project-full-report.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2013/04/samhsa-gains.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2014/06/reducingrecidivism_statesdeliverresults.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2015/09/improving_responses_to_people_with_mental_illnesses_at_the_pretrial_stage_essential_elements.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2017/01/a-five-level-risk-and-needs-system_report.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2017/04/meu-program-outline-arpitl-2017.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2019/04/police-mental-health-collaborations-framework.pdf",
  "https://csgjusticecenter.org/wp-content/uploads/2020/02/reentry_partnership_web-1.pdfv",
  "https://digitalcommons.law.yale.edu/cgi/viewcontent.cgi?article=6155&context=fss_papers",
  "https://effectivehealthcare.ahrq.gov/topics/mental-illness-adults-prisons/research-protocol.",
  "https://fas.org/sgp/crs/misc/lsb10516.pdf",
  "https://fas.org/sgp/crs/misc/r42066.pdf",
  "https://fas.org/sgp/crs/misc/r44087.pdf",
  "https://fas.org/sgp/crs/misc/r45410.pdf",
  "https://fas.org/sgp/crs/misc/rl34287.pdf",
  "https://fsph.iupui.edu/doc/research-centers/overdose-fatality-review-20181010.pdf",
  "https://github.com/icjia/adult-redeploy-client-next",
  "https://github.com/icjia/arrest_explorer",
  "https://github.com/icjia/arrest-explorer-api",
  "https://github.com/icjia/arrest-explorer",
  "https://github.com/icjia/icjia-arrest-explorer-docs",
  "https://gloucesterpd.com/addicts/",
  "https://icjia.illinois.gov/arrestexplorer/docs/arrestexplorer/docs/data.html",
  "https://icjia.illinois.gov/arrestexplorer/docs/data",
  "https://idot.illinois.gov/assets/uploads/files/transportation-system/reports/safety/traffic-stop-studies/2020/final--part%20i%20executive%20summary%202020%20traffic%20stops--6-24-21.pdf",
  "https://lawcenter.giffords.org/wp-content/uploads/2017/12/investing-in-intervention-12.18.17.pdf",
  "https://maps.everytownresearch.org/wp-content/uploads/2020/04/every-state-fact-sheet-2.0-042720-illinois.pdf",
  "https://namsdl.org/wp-content/uploads/model-deflection-to-treatment-act.pdf",
  "https://ndcrc.org/wp-content/uploads/2019/02/aupoliceissuebrief.pdf",
  "https://newsatjama.jama.com/2018/01/03/jama-forum-a-new-years-wish-on-opioids/",
  "https://nicic.gov/basics-and-beyond-suicide-prevention-jails",
  "https://nicic.gov/evidence-based-practices-ebp",
  "https://nicic.gov/thinking-change-40",
  "https://nicic.gov/thinking-for-a-change",
  "https://pdfs.semanticscholar.org/6f7c/e3448572672c4c086a44fc9fd360e8817367.pdf",
  "https://pewrsr.ch/2llbaur",
  "https://privacyruleandresearch.nih.gov/clin_research.asp",
  "https://providencecenter.org/services/crisis-emergency-care/anchored",
  "https://psychopharmacologyinstitute.com/clinical-psychiatry/substance-use-disorders/buprenorphine-formulations-practical-summary-clinicians/",
  "https://reachinstitute.asu.edu/programs/positivefamilysupport",
  "https://ric-zai-inc.com/publications/cops-p356-pub.pdf",
  "https://ric-zai-inc.com/publications/cops-w0869-pub.pdf",
  "https://rockfordil.gov/wp-content/uploads/2021/03/1.06.pdf",
  "https://socialwork.utah.edu/_documents/statewide-ut-mhc-study_part-1-report.pdf",
  "https://store.samhsa.gov/product/family-psychoeducation-evidence-based-practices-ebp-kit/sma09-4423",
  "https://store.samhsa.gov/product/illness-management-and-recovery-evidence-based-practices-ebp-kit/sma09-4463",
  "https://store.samhsa.gov/product/integrated-treatment-for-co-occurring-disorders-evidence-based-practices-ebp-kit/sma08-4367",
  "https://store.samhsa.gov/product/medteam-medication-treatment-evaluation-and-management-evidence-based-practices-ebp-kit/sma10-4549",
  "https://store.samhsa.gov/product/permanent-supportive-housing-evidence-based-practices-ebp-kit-/sma10-4510",
  "https://store.samhsa.gov/product/supported-employment-evidence-based-practices-ebp-kit/sma08-4365",
  "https://store.samhsa.gov/shin/content/ms974/ms974.pdf",
  "https://store.samhsa.gov/shin/content/sma14-4884/sma14-4884.pdf",
  "https://store.samhsa.gov/shin/content/sma18-5063fulldoc/sma18-5063fulldoc.pdf",
  "https://store.samhsa.gov/system/files/sma15-4426.pdf",
  "https://store.samhsa.gov/system/files/sma19-5097.pdf",
  "https://testcountry.com/blogs/drug-testing/how-to-read-a-drug-test-cup",
  "https://www.aecf.org/m/resourcedoc/aecf-reentryandbarrierstoemp-2016.pdf",
  "https://www.americanbar.org/advocacy/the-aba-task-force-on-legal-needs-arising-out-of-the-2020-pandem/",
  "https://www.aurora-il.org/documentcenter/view/7383/apd-use-of-force-policy",
  "https://www.beaconhealthoptions.com/wp-content/uploads/asam-lab-consensus-stmt-src-12-13-17-cmmc-12-19-17.pdf",
  "https://www.beckinstitute.org/wp-content/uploads/2017/08/question-answer-packet-2010.pdf",
  "https://www.bjatraining.org/tools/naloxone/naloxone+background",
  "https://www.bloomberg.com/news/articles/2020-03-30/stuck-at-home-americans-get-robbed-less-often-but-fight-more;wilkins",
  "https://www.blueprintsprograms.org/factsheet/raising-healthy-children",
  "https://www.bop.gov/coronavirus/",
  "https://www.cdc.gov/coronavirus/2019-ncov/community/correction-detention/guidance-correctional-detention.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/community/guidance-business-response.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/community/homeless-shelters/plan-prepare-respond.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/community/index.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/community/organizations/index.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/daily-life-coping/managing-stress-anxiety.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/downloads/guidance-law-enforcement.pdf",
  "https://www.cdc.gov/coronavirus/2019-ncov/hcp/guidance-for-ems.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/need-extra-precautions/unsheltered-homelessness.html",
  "https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/prevention.html?cdc_aa_refval=https%3a%2f%2fwww.cdc.gov%2fcoronavirus%2f2019-ncov%2fprepare%2fprevention.html",
  "https://www.cdc.gov/drugoverdose/maps/rxstate2016.html",
  "https://www.cdc.gov/flu/pandemic-resources/2009-h1n1-pandemic.html",
  "https://www.cdc.gov/healthyyouth/data/ybrs/results.htm",
  "https://www.cdc.gov/violenceprevention/childabuseandneglect/acestudy/about.html",
  "https://www.cdc.gov/violenceprevention/pdf/2015data-brief508.pdf",
  "https://www.cdc.gov/violenceprevention/pdf/nisvs-statereportbook.pdf",
  "https://www.cdc.gov/violenceprevention/suicide/riskprotectivefactors.html",
  "https://www.cdc.gov/violenceprevention/youthviolence/riskprotectivefactors.html",
  "https://www.cdcr.ca.gov/juvenile_justice/docs/dbt_evidence_draft_04_06_2011.pdf",
  "https://www.cdcr.ca.gov/parole/mental-health-services-continuum-program.html",
  "https://www.chicago.gov/content/dam/city/depts/cdph/healthprotectionandresponse/covid-19%20guidance%20for%20homeless%20shelters%20final%2003.20.2020.pdf",
  "https://www.chicago.gov/content/dam/city/sites/public-safety-and-violenc-reduction/pdfs/ourcityoursafety.pdf",
  "https://www.chicagotribune.com/coronavirus/ct-domestic-violence-cutbacks-20200402-2w2nqjvwujb7tkltn4i5xvsck4-story.html?int=lat_digitaladshouse_bx-modal_acquisition-subscriber_ngux_display-ad-interstitial_bx-bonus-story",
  "https://www.childtrends.org/programs/linking-the-interests-of-families-and-teachers-lift",
  "https://www.cognitivecentre.ca/content/rr2",
  "https://www.cookcountysheriff.org/covid-19-cases-at-ccdoc/",
  "https://www.crj.org/training-assessments/cognitive-interaction-skills-cis-core-correctional-practices-ccp/",
  "https://www.dallasbar.org/book-page/dallas-county-innovative-approach-dealing-mental-illness",
  "https://www.div12.org/assessing-violence/",
  "https://www.drugabuse.gov/about-nida/legislative-activities/testimony-to-congress/2015/americas-addiction-to-opioids-heroin-prescription-drug-abuse",
  "https://www.drugabuse.gov/about-nida/organization/workgroups-interest-groups-consortia/community-epidemiology-work-group-cewg/meeting-reports/highlights-summaries-january-2014-2",
  "https://www.drugabuse.gov/publications/preventing-drug-abuse-among-children-adolescents/preface",
  "https://www.drugabuse.gov/publications/principles-drug-addiction-treatment-research-based-guide-third-edition/evidence-based-approaches-to-drug-addiction-treatment/behavioral-0",
  "https://www.drugabuse.gov/publications/principles-drug-addiction-treatment-research-based-guide-third-edition/evidence-based-approaches-to-drug-addiction-treatment/behavioral-2",
  "https://www.drugabuse.gov/publications/principles-drug-addiction-treatment-research-based-guide-third-edition/evidence-based-approaches-to-drug-addiction-treatment/behavioral-3",
  "https://www.drugabuse.gov/publications/principles-drug-addiction-treatment-research-based-guide-third-edition/frequently-asked-questions/use-medications-methadone-buprenorphine",
  "https://www.drugabuse.gov/publications/principles-drug-addiction-treatment/evidence-based-approaches-to-drug-addiction-treatment/behavioral-therapies",
  "https://www.drugabuse.gov/publications/research-reports/therapeutic-communities/how-are-therapeutic-communities-integrated-criminal-justice-system",
  "https://www.drugabuse.gov/sites/default/files/files/dast-10.pdf",
  "https://www.edweek.org/ew/articles/2018/06/22/gunshot-detection-technology-coming-to-wisconsin_ap.html",
  "https://www.equalityhumanrights.com/en/publication-download/research-report-86-impact-changes-commissioning-and-funding-women-only-services",
  "https://www.ers.usda.gov/webdocs/datafiles/53180/25568_il.pdf?v=0",
  "https://www.fbi.gov/about-us/cjis/cjis-link/april-2015/new-initiative-aims-to-increase-crime-reporting-in-nibrs",
  "https://www.fd.org/docs/select-topics---bop/bop-rdap-chart-6-14-10-modified.pdf",
  "https://www.fd.org/sites/default/files/criminal_defense_topics/essential_topics/sentencing_resources/useful_reports/collateral-consequences-resource-list.pdf",
  "https://www.fda.gov/news-events/press-announcements/statement-fda-commissioner-scott-gottlieb-md-agencys-continued-efforts-promote-safe-adoption",
  "https://www.fda.gov/newsevents/productsapprovals/ucm106288.htm",
  "https://www.ilcadv.org/about_icadv/herstory.html",
  "https://www.ilcadv.org/resources/services_guidelines/servicesguidelinesmanual-june2017.pdf",
  "https://www.iljp.org/hb-3653",
  "https://www.improvingmipractices.org/practice-areas/cognitive-behavior-therapy/dialectical-behavior-therapy",
  "https://www.improvingmipractices.org/practices/motivational-enhancement-motivational-interviewing",
  "https://www.justice.gov/file/822231/download",
  "https://www.luc.edu/media/lucedu/ccj/pdfs/firearmpossessionsentencinginillinois.pdf",
  "https://www.memphispolice.org/initiatives.asp",
  "https://www.mind.org.uk/media-a/2942/mental-health-problems-introduction-2017.pdf",
  "https://www.naco.org/articles/%e2%80%98safe-stations%e2%80%99-program-offers-path-recovery-opioid-heroin-addicts.",
  "https://www.nami.org/find-support/living-with-a-mental-health-condition/securing-stable-housing",
  "https://www.nasmhpd.org/content/damaging-consequences-violence-and-trauma-facts-discussion-points-and-recommendations",
  "https://www.nasmhpd.org/content/trauma-addictions-mental-health-and-recovery-tamar-treatment-manual-and-modules",
  "https://www.nccdglobal.org/blog/covid-19-and-justice-system",
  "https://www.ncchc.org/covid-resources",
  "https://www.ncchc.org/facilities",
  "https://www.ncchc.org/opioid-treatment-programs-2",
  "https://www.ncchc.org/staffing-1",
  "https://www.ncfrp.org/cdr/cdr-process/",
  "https://www.ncja.org/ncja/ncja-services/grants-management/federal-grants-process",
  "https://www.ncja.org/state-agencies/agency-contact",
  "https://www.ncjrs.gov/app/publications/abstract.aspx?id=260431",
  "https://www.ncsc.org/~/media/files/pdf/topics/criminal/effective-court-responses-mental-disorders.ashx",
  "https://www.ncsl.org/print/cj/mentaljjneeds.pdf",
  "https://www.ncsl.org/research/civil-and-criminal-justice/criminal-justice-and-covid-19.aspx",
  "https://www.nimh.nih.gov/health/publications/post-traumatic-stress-disorder-ptsd/ptsd-508-05172017_38054.pdf",
  "https://www.ovcttac.gov/downloads/views/trainingmaterials/nvaa/documents_nvaa2011/resourcepapers/color_child_abuse_resource_paper_2012_final_-_508c_9_13_2012.pdf",
  "https://www.ovcttac.gov/downloads/views/trainingmaterials/nvaa/documents_nvaa2011/resourcepapers/color_child%20abuse%20resource%20paper%202012_final%20-%20508c_9_13_2012.pdf",
  "https://www.prainc.com/wp-content/uploads/2015/10/article-integrating-mental-health-substance-abuse-services-justice-involved-persons.pdf",
  "https://www.prainc.com/wp-content/uploads/2015/10/article-supported-employment-justice-involved-people-mental-illness.pdf",
  "https://www.prainc.com/wp-content/uploads/2015/10/fact-sheet-illness-management-recovery.pdf",
  "https://www.prainc.com/wp-content/uploads/2016/10/housing072616.pdf",
  "https://www.primetherapeutics.com/content/dam/corporate/documents/newsroom/primeinsights/2016/amcp16fl-opioids.pdf",
  "https://www.psychiatry.org/patients-families/what-is-telepsychiatry",
  "https://www.roosevelt.edu/cas/centersandinstitutes/ima/icdp.aspx",
  "https://www.rrstar.com/news/20181006/less-gunfire-detected-in-rockford-despite-new-shotspotter-technology",
  "https://www.samhsa.gov/medication-assisted-treatment/about",
  "https://www.samhsa.gov/medication-assisted-treatment/buprenorphine-waiver-management/qualify-for-physician-waiver",
  "https://www.samhsa.gov/medication-assisted-treatment/training-materials-resources/apply-for-practitioner-waiver",
  "https://www.samhsa.gov/medication-assisted-treatment/treatment",
  "https://www.samhsa.gov/medication-assisted-treatment/treatment/buprenorphine",
  "https://www.samhsa.gov/medication-assisted-treatment/treatment/methadone",
  "https://www.samhsa.gov/nctic",
  "https://www.samhsa.gov/nctic/trauma-interventions",
  "https://www.samhsa.gov/samhsanewsletter/volume_22_number_2/trauma_tip/guiding_principles.html",
  "https://www.samhsa.gov/sites/default/files/20190718-samhsa-risk-protective-factors.pdf",
  "https://www.santafenm.gov/news/detail/prevention_alliance_sffd_county_partner_to_expand_narcan_access_",
  "https://www.surveygizmo.com/resources/blog/survey-response-rates/",
  "https://www.techsafety.org/covid19",
  "https://www.thenationalcouncil.org/wp-content/uploads/2012/11/dla-sample.pdf?daf=375atetbd56",
  "https://www.uc.edu/content/dam/uc/ccjr/docs/reports/final%20ocjs%20report%202.22.13.pdf.",
  "https://www.unidosus.org/publications/1213-lost-opportunities-the-reality-of-latinos-in-the-u-s-criminal-justice-system/",
  "https://www.usaid.gov/sites/default/files/usaid-2016-what-works-in-reducing-community-violence-final-report.pdf",
  "https://www.vera.org/publication_downloads/new-normal-opioid-use-criminal-justice-system/new-normal-opioid-use-criminal-justice-system.pdf",
  "https://www.whitehouse.gov/briefing-room/statements-releases/2021/06/23/fact-sheet-biden-harris-administration-announces-comprehensive-strategy-to-prevent-and-respond-to-gun-crime-and-ensure-public-safety/",
  "https://www.whitehouse.gov/sites/default/files/docs/licensing_report_final_nonembargo.pdf",
  "https://www.whitehouse.gov/sites/default/files/page/files/synthetic_drugs_fact_sheet_455_2_15_12.pdf",
  "https://www.whitehouse.gov/sites/whitehouse.gov/files/images/final%20standard%20size%20of%20fentanyl%20safety%20recommendations%20for%20first%20respond....pdf",
  "https://www.who.int/mental_health/policy/mh_in_prison.pdf",
  "https://www.who.int/substance_abuse/publications/en/positionpaper_english.pdf?ua=1",
  "https://www.who.int/substance_abuse/publications/opioid_dependence_guidelines.pdf",
  "https://www2.ed.gov/policy/gen/guid/fpco/ferpa/students.html",
];

/**
 * List of expired-grant / expired-opportunity URLs.
 *
 * Semantically distinct from BROKEN_URLS: the URL still resolves (no
 * 4xx/5xx), but the underlying resource is an expired funding
 * opportunity that no one can act on anymore. Editorial wants these
 * unwrapped to plain text so users can't click into a dead end, and
 * so short non-descriptive link text (e.g. "here") stops triggering
 * sia-r14 / WCAG 2.4.4 flags on pages that reference the opportunity.
 *
 * Unwrapped by the same `unwrapBrokenLinks` plugin in
 * contentSanitizer.js — the pipeline treats both lists identically.
 */
const EXPIRED_URLS = [
  // IFVCC Planning NOFO #2096-2611 — expired grant opportunity
  // Referenced on /grants/funding/ifvcc-planning-nofo-2096-2611/
  "https://il.amplifund.com/public/opportunities/details/4337e6e0-27fe-4d86-84fd-53d990fac031",
];

// Strip a single trailing punctuation char (`.`, `,`, `;`) — CMS authors
// commonly write "see http://example.com." which makes the period part
// of the href. Comparison treats both forms as the same URL.
function normalize(url) {
  if (!url) return "";
  let u = url.trim().toLowerCase();
  if (/[.,;]$/.test(u)) u = u.slice(0, -1);
  return u;
}

const BROKEN_SET = new Set([...BROKEN_URLS, ...EXPIRED_URLS].map(normalize));

/**
 * Returns true if the given URL is on the confirmed-broken or
 * expired-grant lists. Comparison is case-insensitive and tolerant
 * of one trailing punctuation character.
 */
function isBrokenUrl(url) {
  if (!url) return false;
  return BROKEN_SET.has(normalize(url));
}

export { BROKEN_URLS, isBrokenUrl };
